version: "3"
services:
  postgres:
    image: postgres:13-alpine
    volumes :
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=${PSQL_DATABASE}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PSQL_USER}", "-d", "${PSQL_DATABASE}"]
      interval: 5s
      timeout: 10s
      retries: 5
      #  redis:
      #    container_name: redis
      #    image: redis/redis-stack-server:latest
      #    volumes :
      #      - redis:/data
      #    environment:
      #      - REDIS_ARGS=--save 900 1 --save 300 10 --save 60 10000 
      #    ports:
      #      - 6379:6379
volumes:
  postgres:
  redis:
